import React, { useState, useEffect } from 'react';
import api from '../utils/api';
import { Layers, Sparkles, Loader2, ArrowRight, RotateCw, CheckCircle, RotateCcw, Trash2 } from 'lucide-react';

interface Flashcard {
  _id: string;
  front: string;
  back: string;
  status: 'learned' | 'review';
}

interface DocumentOption {
  _id: string;
  name: string;
}

export const FlashcardsPage: React.FC = () => {
  const [flashcards, setFlashcards] = useState<Flashcard[]>([]);
  const [documents, setDocuments] = useState<DocumentOption[]>([]);
  
  // Selection/Generation state
  const [selectedDocId, setSelectedDocId] = useState('');
  const [generateCount, setGenerateCount] = useState(10);
  const [generating, setGenerating] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  // Study Deck state
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);

  useEffect(() => {
    fetchDocuments();
    fetchFlashcards();
  }, []);

  const fetchDocuments = async () => {
    try {
      const response = await api.get('/documents');
      const readyDocs = response.data.documents.filter((d: any) => d.status === 'ready');
      setDocuments(readyDocs);
    } catch (err) {
      console.error(err);
    }
  };

  const fetchFlashcards = async () => {
    setLoading(true);
    try {
      const response = await api.get('/flashcards');
      setFlashcards(response.data.flashcards);
      setCurrentIndex(0);
      setIsFlipped(false);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedDocId) {
      setError('Please select a document to generate flashcards.');
      return;
    }

    setError('');
    setGenerating(true);
    try {
      await api.post('/flashcards/generate', {
        documentId: selectedDocId,
        count: generateCount,
      });
      await fetchFlashcards();
    } catch (err: any) {
      setError(err.response?.data?.message || 'Error generating flashcards');
    } finally {
      setGenerating(false);
    }
  };

  const handleToggleStatus = async (id: string, currentStatus: 'learned' | 'review') => {
    const nextStatus = currentStatus === 'learned' ? 'review' : 'learned';
    try {
      await api.patch(`/flashcards/${id}`, { status: nextStatus });
      setFlashcards((prev) =>
        prev.map((card) => (card._id === id ? { ...card, status: nextStatus } : card))
      );
    } catch (err) {
      console.error('Error updating flashcard status:', err);
    }
  };

  const handleDeleteCard = async (id: string) => {
    if (!confirm('Delete this flashcard?')) return;
    try {
      await api.delete(`/flashcards/${id}`);
      setFlashcards((prev) => prev.filter((card) => card._id !== id));
      if (currentIndex >= flashcards.length - 1 && currentIndex > 0) {
        setCurrentIndex((prev) => prev - 1);
      }
      setIsFlipped(false);
    } catch (err) {
      console.error('Error deleting card:', err);
    }
  };

  const handleDeleteAllCards = async () => {
    if (!confirm('Are you sure you want to delete ALL flashcards? This action cannot be undone.')) return;
    try {
      await api.delete('/flashcards');
      setFlashcards([]);
      setCurrentIndex(0);
      setIsFlipped(false);
    } catch (err) {
      console.error('Error deleting all flashcards:', err);
    }
  };

  const handleNext = () => {
    if (currentIndex < flashcards.length - 1) {
      setIsFlipped(false);
      setTimeout(() => {
        setCurrentIndex((prev) => prev + 1);
      }, 150);
    }
  };

  const handlePrev = () => {
    if (currentIndex > 0) {
      setIsFlipped(false);
      setTimeout(() => {
        setCurrentIndex((prev) => prev - 1);
      }, 150);
    }
  };

  const learnedCount = flashcards.filter((c) => c.status === 'learned').length;
  const progressPercent = flashcards.length > 0 ? Math.round((learnedCount / flashcards.length) * 100) : 0;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Flashcard Deck</h1>
        <p className="text-sm text-muted-foreground">Test your memory and study key definitions generated by the AI study pipeline.</p>
      </div>

      {error && (
        <div className="p-3 bg-red-950/40 border border-red-500/20 text-red-400 text-sm rounded-xl">
          {error}
        </div>
      )}

      {/* Generation Panel */}
      <div className="bg-card border border-border rounded-2xl p-5 shadow-sm">
        <h2 className="font-semibold text-base flex items-center gap-2 mb-4">
          <Sparkles className="h-5 w-5 text-violet-500" />
          Generate New Flashcards
        </h2>

        <form onSubmit={handleGenerate} className="flex flex-wrap items-end gap-4">
          <div className="flex-1 min-w-[200px]">
            <label className="text-xs text-muted-foreground block mb-1.5 font-medium">Select Source PDF:</label>
            <select
              value={selectedDocId}
              onChange={(e) => setSelectedDocId(e.target.value)}
              className="w-full bg-secondary border border-border text-foreground text-sm rounded-xl px-3 py-2.5 focus:outline-none focus:ring-1 focus:ring-primary cursor-pointer"
            >
              <option value="">-- Choose Document --</option>
              {documents.map((d) => (
                <option key={d._id} value={d._id}>
                  {d.name}
                </option>
              ))}
            </select>
          </div>

          <div className="w-28">
            <label className="text-xs text-muted-foreground block mb-1.5 font-medium">Card Quantity:</label>
            <select
              value={generateCount}
              onChange={(e) => setGenerateCount(Number(e.target.value))}
              className="w-full bg-secondary border border-border text-foreground text-sm rounded-xl px-3 py-2.5 focus:outline-none focus:ring-1 focus:ring-primary cursor-pointer"
            >
              <option value={5}>5 Cards</option>
              <option value={10}>10 Cards</option>
              <option value={15}>15 Cards</option>
            </select>
          </div>

          <button
            type="submit"
            disabled={generating || documents.length === 0}
            className="flex items-center justify-center gap-2 px-5 py-2.5 bg-primary text-primary-foreground hover:bg-primary/95 text-sm font-semibold rounded-xl disabled:opacity-50 disabled:cursor-not-allowed transition-all"
          >
            {generating ? (
              <>
                <Loader2 className="animate-spin h-4 w-4" /> Generating Cards...
              </>
            ) : (
              <>
                Generate Cards <ArrowRight className="h-4 w-4" />
              </>
            )}
          </button>
        </form>
        {documents.length === 0 && (
          <p className="text-xs text-amber-500 mt-2">
            No processed documents available. Upload notes first.
          </p>
        )}
      </div>

      {/* Main Flashcard Review Area */}
      {loading ? (
        <div className="py-24 text-center text-muted-foreground flex flex-col items-center justify-center">
          <Loader2 className="animate-spin h-8 w-8 text-primary mb-2" />
          <p className="text-sm">Loading flashcards...</p>
        </div>
      ) : flashcards.length === 0 ? (
        <div className="border border-border bg-card/40 rounded-2xl py-16 text-center text-muted-foreground max-w-md mx-auto">
          <Layers className="h-12 w-12 mx-auto mb-3 opacity-30" />
          <p className="font-semibold text-sm mb-1">No Flashcards Yet</p>
          <p className="text-xs px-6">Select a document above to generate a card deck, or complete uploads to begin study review.</p>
        </div>
      ) : (
        <div className="max-w-xl mx-auto space-y-6">
          {/* Progress Indicator */}
          <div className="bg-card border border-border rounded-2xl p-4 shadow-sm">
            <div className="flex justify-between items-center text-xs mb-2">
              <span className="text-muted-foreground">Deck Review Progress</span>
              <div className="flex items-center gap-3">
                <span className="font-semibold">{learnedCount} / {flashcards.length} Learned ({progressPercent}%)</span>
                <button
                  onClick={handleDeleteAllCards}
                  className="flex items-center gap-1 text-red-500 hover:text-red-600 hover:bg-red-500/10 px-2 py-1 rounded-lg transition-all font-semibold"
                  title="Delete all flashcards"
                >
                  <Trash2 className="h-3 w-3" /> Clear Deck
                </button>
              </div>
            </div>
            <div className="w-full bg-secondary h-2.5 rounded-full overflow-hidden">
              <div 
                className="bg-emerald-500 h-full transition-all duration-300 rounded-full" 
                style={{ width: `${progressPercent}%` }}
              />
            </div>
          </div>

          {/* Flashcard Terminal */}
          <div className="h-80 w-full relative">
            <div 
              className={`flip-card w-full h-full cursor-pointer select-none ${isFlipped ? 'flipped' : ''}`}
              onClick={() => setIsFlipped(!isFlipped)}
            >
              <div className="flip-card-inner">
                {/* Front Side */}
                <div className="flip-card-front bg-card border border-border p-8 flex flex-col justify-between shadow-md">
                  <div className="flex justify-between text-xs text-muted-foreground font-semibold">
                    <span className="uppercase tracking-wider">Concept Question</span>
                    <span>Card {currentIndex + 1} of {flashcards.length}</span>
                  </div>
                  <div className="flex-1 flex items-center justify-center py-4 text-center">
                    <p className="text-lg font-bold leading-normal text-foreground px-4">
                      {flashcards[currentIndex].front}
                    </p>
                  </div>
                  <div className="text-xs text-muted-foreground flex items-center justify-center gap-1.5 font-medium">
                    <RotateCw className="h-3.5 w-3.5 text-primary" /> Click card to flip and view explanation
                  </div>
                </div>

                {/* Back Side */}
                <div className="flip-card-back bg-card border border-border p-8 flex flex-col justify-between shadow-md">
                  <div className="flex justify-between text-xs text-muted-foreground font-semibold">
                    <span className="uppercase tracking-wider text-violet-400">Answer Key</span>
                    <span>Card {currentIndex + 1} of {flashcards.length}</span>
                  </div>
                  <div className="flex-1 flex items-center justify-center py-4 text-center overflow-y-auto">
                    <p className="text-sm text-foreground dark:text-zinc-300 leading-relaxed font-normal max-h-[160px] px-2 whitespace-pre-wrap">
                      {flashcards[currentIndex].back}
                    </p>
                  </div>
                  <div className="text-xs text-muted-foreground flex items-center justify-center gap-1.5 font-medium">
                    <RotateCw className="h-3.5 w-3.5 text-primary" /> Click card to return to question
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Cards Navigator Actions */}
          <div className="flex items-center justify-between gap-4">
            <button
              onClick={handlePrev}
              disabled={currentIndex === 0}
              className="px-4 py-2 border border-border hover:bg-secondary text-sm font-semibold rounded-xl disabled:opacity-40 disabled:cursor-not-allowed transition-all"
            >
              Previous Card
            </button>

            <div className="flex gap-2">
              <button
                onClick={() => handleToggleStatus(flashcards[currentIndex]._id, flashcards[currentIndex].status)}
                className={`flex items-center gap-1.5 px-4 py-2 text-xs font-bold rounded-xl transition-all shadow-sm ${
                  flashcards[currentIndex].status === 'learned'
                    ? 'bg-emerald-500/10 text-emerald-500 border border-emerald-500/20'
                    : 'bg-zinc-800 text-muted-foreground hover:text-foreground border border-border'
                }`}
              >
                {flashcards[currentIndex].status === 'learned' ? (
                  <>
                    <CheckCircle className="h-4 w-4" /> Learned
                  </>
                ) : (
                  <>
                    <RotateCcw className="h-4 w-4" /> Review Pending
                  </>
                )}
              </button>
              
              <button
                onClick={() => handleDeleteCard(flashcards[currentIndex]._id)}
                className="p-2 border border-border text-muted-foreground hover:text-red-500 hover:bg-red-500/10 rounded-xl transition-all"
                title="Delete card"
              >
                <Trash2 className="h-4 w-4" />
              </button>
            </div>

            <button
              onClick={handleNext}
              disabled={currentIndex === flashcards.length - 1}
              className="px-4 py-2 border border-border hover:bg-secondary text-sm font-semibold rounded-xl disabled:opacity-40 disabled:cursor-not-allowed transition-all"
            >
              Next Card
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
